name: Keep Supabase Awake

on:
  schedule:
    # Run every 11 hours (at 0:00, 11:00, and 22:00 UTC)
    - cron: '0 0,11,22 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase
        run: |
          echo "Pinging Supabase to keep it awake..."
          # Replace YOUR_DOMAIN with your actual domain
          curl -f -X GET "https://YOUR_DOMAIN.vercel.app/api/ping" || echo "Ping failed, but continuing..."
          echo "Ping completed at $(date)"
      
      - name: Log ping result
        run: echo "Supabase ping job completed successfully"
